export const eventsByDay = {
  '2024-09-09': [
    {
      id: '1',
      genre: 'barspe',
      name: 'BARSPE MUSEE',
      date: '2024-09-09',
      location: '48.860611,2.337644', // Coordonnées GPS du Musée
      startTime: '17',
      endTime: '18',
      duration: '1',
      assos: ['adr'],
      logo: 'adr',
      description: '',
    },
    {
      id: '2',
      genre: 'acti',
      name: 'ACTI WEI',
      date: '2024-09-09',
      location: '48.860611,2.337644', // Coordonnées GPS du Musée
      startTime: '12',
      endTime: '13',
      duration: '1',
      assos: ['wei'],
      logo: 'wei',
      description: 'Description de l\'activité.',
    },
    {
      id: '7',
      genre: 'bar',
      name: 'BARSPE EXTRA',
      date: '2024-09-09',
      location: 'Campus Bar',
      startTime: '17',
      endTime: '18:30',
      duration: '1.5',
      assos: ['wei'],
      logo: 'wei',
      description: 'Se chevauche avec BARSPE MUSEE.',
    },
    {
      id: '8',
      genre: 'sport',
      name: 'Yoga Session',
      date: '2024-09-09',
      location: 'Gym',
      startTime: '16',
      endTime: '17:30',
      duration: '1.5',
      assos: ['sport'],
      logo: 'sport',
      description: 'Chevauchement partiel avec BARSPE MUSEE.',
    },
    {
      id: '12',
      genre: 'meeting',
      name: 'Réunion Sponsors',
      date: '2024-09-09',
      location: 'Salle A',
      startTime: '16:30',
      endTime: '17:30',
      duration: '1',
      assos: ['team'],
      logo: 'team',
      description: 'Chevauchement avec Yoga Session et BARSPE MUSEE.',
    },
  ],
  '2024-09-10': [
    {
      id: '3',
      genre: 'game',
      name: 'Escape Game',
      date: '2024-09-10',
      location: 'Carré des sciences',
      startTime: '10',
      endTime: '12',
      duration: '2',
      assos: ['esc'],
      logo: 'esc',
      description: '',
    },
    {
      id: '4',
      genre: 'sport',
      name: 'Tournoi de sport BDS',
      date: '2024-09-10',
      location: 'Plaine des sports',
      startTime: '15',
      endTime: '17',
      duration: '2',
      assos: ['bds'],
      logo: 'bds',
      description: '',
    },
    {
      id: '9',
      genre: 'meeting',
      name: 'Réunion Team',
      date: '2024-09-10',
      location: 'Salle 101',
      startTime: '15:30',
      endTime: '16:30',
      duration: '1',
      assos: ['team'],
      logo: 'team',
      description: 'Chevauchement avec Tournoi de sport BDS.',
    },
    {
      id: '13',
      genre: 'talk',
      name: 'Conférence développement durable',
      date: '2024-09-10',
      location: 'Amphithéâtre',
      startTime: '15:15',
      endTime: '16:45',
      duration: '1.5',
      assos: ['green'],
      logo: 'green',
      description: 'Chevauchement avec Tournoi de sport BDS et Réunion Team.',
    },
  ],
  '2024-09-11': [
    {
      id: '5',
      genre: 'bar',
      name: 'Barspé ForumxCU',
      date: '2024-09-11',
      location: 'Carré des sciences',
      startTime: '14',
      endTime: '16',
      duration: '2',
      assos: ['cu'],
      logo: 'cu',
      description: '',
    },
    {
      id: '10',
      genre: 'workshop',
      name: 'Atelier cuisine',
      date: '2024-09-11',
      location: 'Cuisine du campus',
      startTime: '15',
      endTime: '16:30',
      duration: '1.5',
      assos: ['cuisine'],
      logo: 'cuisine',
      description: 'Chevauchement avec Barspé ForumxCU.',
    },
    {
      id: '14',
      genre: 'sport',
      name: 'Initiation Escrime',
      date: '2024-09-11',
      location: 'Gym',
      startTime: '15:30',
      endTime: '17',
      duration: '1.5',
      assos: ['escrime'],
      logo: 'escrime',
      description: 'Chevauchement avec Atelier cuisine et Barspé ForumxCU.',
    },
  ],
  '2024-09-12': [
    {
      id: '6',
      genre: 'beach',
      name: 'Tournoi beach CheerUp',
      date: '2024-09-12',
      location: 'Derrière Rez 2C',
      startTime: '16',
      endTime: '18',
      duration: '2',
      assos: ['cheerup'],
      logo: 'cheerup',
      description: '',
    },
    {
      id: '11',
      genre: 'bar',
      name: 'Soirée Barbecue',
      date: '2024-09-12',
      location: 'Cour principale',
      startTime: '17:30',
      endTime: '19',
      duration: '1.5',
      assos: ['bbq'],
      logo: 'bbq',
      description: 'Chevauchement partiel avec Tournoi beach CheerUp.',
    },
    {
      id: '15',
      genre: 'talk',
      name: 'Discussion Alumni',
      date: '2024-09-12',
      location: 'Amphithéâtre',
      startTime: '17',
      endTime: '18:30',
      duration: '1.5',
      assos: ['alumni'],
      logo: 'alumni',
      description: 'Chevauchement avec Tournoi beach CheerUp et Soirée Barbecue.',
    },
  ],
};